Finished day 4
JustynaPuz/advent-of-code-23 pull request #3
Opened 2023-12-05 20:25 UTC by JustynaPuz

2023-12-09 14:53 UTC, baranskixx requested changes

2023-12-09 14:53 UTC, baranskixx commented on src/main/java/aoc2023/day4/Main1.java
> +            numbers = line.substring(line.indexOf("|") + 1).trim().split(" {1,2}");
Czemu tam jest taka wartosc w split?

2023-12-09 14:53 UTC, baranskixx commented on src/main/java/aoc2023/day4/Main1.java
> +            String[] winningNumbers;
Zróbmy to inaczej - zapisujmy wygrane liczby oraz zwykle liczby do zbiorów (Set).
[(link do tutoriala na stronie z chmurką co je pizze)](https://www.digitalocean.com/community/tutorials/java-set)

2023-12-09 14:53 UTC, baranskixx commented on src/main/java/aoc2023/day4/Main1.java
> +            for(String s : numbers) {
Tutaj, w związku z użyciem setów sprawdzajmy po prostu ich zbiór wspólny - da nam to odpowiedź w bardziej elegancki sposób

2023-12-09 14:53 UTC, baranskixx commented on src/main/java/aoc2023/day4/Main2.java
> +public class Main2 {
Analogiczne zmiany wprowadź w tym pliku

2023-12-10 21:40 UTC, JustynaPuz commented on src/main/java/aoc2023/day4/Main1.java
> +            numbers = line.substring(line.indexOf("|") + 1).trim().split(" {1,2}");
podziel jesli jest jedna lub dwie spacje, bo moga byc pojedyncze liczby i wtedy dzieliło bez nich bo nie wykrywało dwoch spacji

2023-12-11 14:32 UTC, baranskixx approved these changes
Oki doki

2023-12-11 14:35 UTC, merged